FROM amazoncorretto:11

ARG JAR_FILE=build/libs/*.jar

COPY ${JAR_FILE} app.jar

ARG JWT_SECRET_KEY
ENV KNITTING_JWT_SECRET_KEY ${JWT_SECRET_KEY}

ARG GOOGLE_CLIENT_SECRET
ENV KNITTING_GOOGLE_CLIENT_SECRET ${GOOGLE_CLIENT_SECRET}

ARG POSTGRESQL_PASSWORD
ENV KNITTING_POSTGRES_PASSWORD ${POSTGRESQL_PASSWORD}

ARG SSL_KEY_STORE_PASSWORD
ENV KNITTING_SSL_KEY_STORE_PASSWORD ${SSL_KEY_STORE_PASSWORD}

ARG SSL_KEY_PASSWORD
ENV KNITTING_SSL_KEY_PASSWORD ${SSL_KEY_PASSWORD}

ENTRYPOINT ["java","-jar","/app.jar"]
