ALTER TABLE design ADD COLUMN description VARCHAR NOT NULL;
ALTER TABLE design ADD COLUMN target_level VARCHAR NOT NULL;
ALTER TABLE design ADD COLUMN cover_image_url VARCHAR NOT NULL;
ALTER TABLE design DROP COLUMN price;
